import "./globals.css";
import "@repo/ui/styles.css";
import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const GraphqlProvider = dynamic(
  () => import("@/components/providers/GrapqhlProvider")
);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className={inter.className}>
        <GraphqlProvider>{children}</GraphqlProvider>
      </body>
    </html>
  );
}
